# Generated by Django 5.2.5 on 2025-09-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('basemodeuuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='helpers.basemodeuuid')),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            bases=('helpers.basemodeuuid',),
        ),
    ]
