import type { Metadata } from "next";
import { Geist, Geist_Mono, Modern_Antiqua } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const modern_antique = Modern_Antiqua({
  variable: "--font-modern-antique",
  subsets: ["latin"],
  weight: "400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${modern_antique.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="planks">
          <div className="lg:max-w-7xl lg:mx-auto lg:p-4">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
