# Generated by Django 5.2.5 on 2025-08-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gps_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='address_images/'),
        ),
    ]
