# Generated by Django 5.2.5 on 2025-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        ('users', '0005_address_gps_link_address_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet_preferences',
            field=models.ManyToManyField(null=True, related_name='users', to='diet.dietarypreference'),
        ),
    ]
