# Generated by Django 5.2.5 on 2025-09-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        ('users', '0006_user_diet_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diet_preferences',
            field=models.ManyToManyField(blank=True, related_name='users', to='diet.dietarypreference'),
        ),
    ]
